name: Lint
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch, tag or SHA to checkout.When checking out the repository thattriggered a workflow, this defaults to the reference or SHA for that event.
        required: true
        default: ${{ github.ref }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache temporary
        uses: actions/cache@v3
        with:
          key: tmp-${{ runner.os }}-${{ hashFiles('Makefile.tools') }}
          path: .tmp
      - name: Lint Go
        run: GOLANGCI_LINT_FORMAT="github-actions" make lint-go
      - name: Format
        run: make format
      - name: Lint format
        run: git diff --exit-code
      - name: Lint uncommited
        run: ./scripts/check-uncommited.sh
