name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker push
        if: startsWith(github.ref, 'refs/tags/')
        run: REVISION="${{ github.ref_name }}" make docker-push
  release:
    needs:
      - deploy
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
        arch:
          - "386"
          - amd64
          - arm64
        exclude:
          - os: darwin
            arch: "386"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache temporary
        uses: actions/cache@v3
        with:
          key: tmp-${{ runner.os }}-${{ hashFiles('Makefile.tools') }}
          path: .tmp
      - name: Generate
        run: make gen
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/oklog.${{ matrix.os }}.${{ matrix.arch }}
